#!/usr/bin/env python3
"""Verify sealed B2R09 ATTEMPT-002 sherpa-onnx-compact evidence."""
from __future__ import annotations
import hashlib, json, re, subprocess
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2]; PUBLIC=ROOT/'research'/'000b2-public'; ENTRY=ROOT/'research'/'000b2-entry'
E=PUBLIC/'b2r09-sherpa-onnx-compact.json'; P=PUBLIC/'b2r09-provenance.json'; ATTEMPT=PUBLIC/'attempt-002-manifest.json'; PRE=PUBLIC/'preprocessing-capture.json'; REBIND=PUBLIC/'b2r03-preexecution-rebinding.json'; SMOKE=ENTRY/'operational-smoke-evidence.json'; READY=PUBLIC/'recovery-readiness.json'; TASKS=ROOT/'specs'/'000B2-public-corpus-bakeoff'/'tasks.md'; CURRENT=ROOT/'specs'/'CURRENT.md'; CC=ROOT/'docs'/'canonical'/'CURRENT_STATE.md'
E_SHA='d59fa9605e8b0cf6892cd5a7ece105c6abe0753ff8949e9206e35f42da9a003f'; E_SIZE=248426; PAYLOAD='4a81f1be21e18aa462ee9ec9c32a1daeaa6fa86bcca6372b0634a9421c16c1ed'; P_SHA='d86d04149ec0f6d0f5244ddab109f511da285c2819ab9b7bbe661724e5e8e0f3'; P_PAYLOAD='f217a0538636030cfa9f9f36fdbef11c797558aceda4c9dc12e556202bd9df31'
ATTEMPT_SHA='a2dc8246e4567e670beb3f26e315be93e001e4d9a9037be57ff11fce5a340134'; PRE_SHA='d90e5215081191134d8e714778140bfeee8080eb77aedc3a159b2dfed6e2d011'; REBIND_SHA='f9cda5168e6cafb6a1e9e6898f394ec3987b37af50c53c15cf63bc136c1f2df1'; SMOKE_BLOB='fe02902197e005f82cf1b240fe463f4580fad918'; SMOKE_PAYLOAD='5cf8aa72785a9c906640b18e79f839429739e8713d32a6ef745cefe4143c101c'; DECODER_BLOB='27052cc7f3d57d2743ee06a7db8de730c833935e'
BASE='737e2fa0422e0d1aa0dd4d5bdc0473d51cec624c'; TASK_REV='b7a4bb8828a4b861a399b1424bc07a4e549cf51f'; FAILED='f45e9884e3fbcdc84dd27393b8ffde7d12df65e5'; SUCCESS='47d1c53f6892dda437aa0f1d109f58f1cc5e101e'; FAILED_RUN=34155967652; FAILED_JOB=101847745228; SUCCESS_RUN=34156167567; SUCCESS_JOB=101848322734; WORKFLOW=352553362; ARTIFACT=10031177463; ZIP_SHA='79652728032760ae133845b7f1308623a984ee69c490991cf190d8a7301985ea'
RUNTIME='917bed95c8e5c7c18aa4d69fea42e9ef8ef0a60e'; RUNTIME_TREE='fd2c4e97c9f7499b6ed91c7c2854b4211f61bdc0'; ONNX='6037ea07e3abfe599ad00d418968bcf9656e7472'; AUX='672fbf1b30579d6585301139bb363f42a0ad4a24'; FREEZE='600a286747ef2e1503a48c4138b6e405665ccd6586904ef65b3638b49974bcc8'
CLAIMS={'b2r10_authorized':False,'comparative_performance_authorized':False,'comparative_result_available':False,'human_developer_speech_accuracy_evidence':'ABSENT','product_code_authorized':False,'production_stt_selected':False}
ARTIFACTS=[{'path':'encoder-epoch-99-avg-1-chunk-16-left-128.int8.onnx','sha256':'563fde436d16cf7607cf408cd6b30909819d03162652ef389c2450ced3f45ac1','size_bytes':71083163},{'path':'decoder-epoch-99-avg-1-chunk-16-left-128.int8.onnx','sha256':'98da299f471e38bb4e1a8df579b8cc9122d6039576a77e357b3c60f17dd83b02','size_bytes':1307236},{'path':'joiner-epoch-99-avg-1-chunk-16-left-128.int8.onnx','sha256':'d944208d660d67c8d72cd2acaeac971fa5ceb8c80e76c1968148846fedd6e297','size_bytes':259335},{'path':'bpe.model','sha256':'c53433de083c4a6ad12d034550ef22de68cec62c4f58932a7b6b8b2f1e743fa5','size_bytes':244865},{'path':'tokens.txt','sha256':'49e3c2646595fd907228b3c6787069658f67b17377c60aeb8619c4551b2316fb','size_bytes':5048}]
SHA64=re.compile(r'^[0-9a-f]{64}$')
class VerifyError(ValueError): pass
def req(x:bool,m:str)->None:
    if not x: raise VerifyError(m)
def load(path:Path)->dict[str,Any]:
    v=json.loads(path.read_text(encoding='utf-8')); req(isinstance(v,dict),f'object expected: {path}'); return v
def sha(path:Path)->str:return hashlib.sha256(path.read_bytes()).hexdigest()
def canon(v:Any)->bytes:return (json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))+'\n').encode()
def git(*a:str)->str:return subprocess.run(['git','-C',str(ROOT),*a],check=True,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE).stdout.strip()
def frontier()->None:
    r=load(READY); tasks=TASKS.read_text(); cur=CURRENT.read_text(); cc=CC.read_text(); pre=['B2R01','B2R02','B2R03','B2R04','B2R05','B2R06','B2R07','B2R08']
    req(r.get('state')=='RECOVERY_READY' and r.get('qualified_workflow_change_paths')==[],'recovery authority drift'); g=r.get('claim_guards',{}); req(g.get('comparative_result_available') is False and g.get('production_stt_selected') is False and g.get('product_code_authorized') is False,'recovery claim guard drift')
    if r.get('completed_recovery_tasks')==pre and r.get('active_recovery_unit')=='B2R09': req('- [x] `B2R08`' in tasks and '- [ ] `B2R09`' in tasks and '- [ ] `B2R10`' in tasks and 'active recovery unit `B2R09`' in cur and '**Active recovery unit:** `B2R09`' in cc,'B2R09 frontier drift')
    else: req('B2R09' in r.get('completed_recovery_tasks',[]) and '- [x] `B2R09`' in tasks and r.get('active_recovery_unit')!='B2R09','post-reconciliation B2R09 drift')
def static()->None:
    req(sha(ATTEMPT)==ATTEMPT_SHA and sha(PRE)==PRE_SHA and sha(REBIND)==REBIND_SHA,'frozen authority bytes drift'); req(git('hash-object','research/000b2-public/decode_b2r09.py')==DECODER_BLOB,'decoder blob drift'); req(git('hash-object','research/000b2-entry/operational-smoke-evidence.json')==SMOKE_BLOB,'smoke blob drift')
    for rev in (BASE,TASK_REV,FAILED,SUCCESS): req(git('rev-parse',f'{rev}^{{commit}}')==rev,f'missing source {rev}')
    req(git('rev-parse',f'{SUCCESS}^')==FAILED,'repair parentage drift'); req(git('diff','--name-only',FAILED,SUCCESS).splitlines()==['.github/workflows/internal-b2r09-capture.yml'],'repair scope drift'); patch=git('diff','--unified=0',FAILED,SUCCESS,'--','.github/workflows/internal-b2r09-capture.yml'); req("-          cache: 'pip'" in patch and '+          cache:' not in patch,'repair semantic drift')
def smoke()->None:
    cells=load(SMOKE).get('candidate_evidence'); req(isinstance(cells,list),'smoke cells missing'); xs=[x for x in cells if x.get('candidate_id')=='sherpa-onnx-compact']; req(len(xs)==1,'smoke cell cardinality drift'); x=xs[0]; req(x.get('evidence_payload_sha256')==SMOKE_PAYLOAD and x.get('status')=='SMOKE_PASS','smoke payload/status drift'); req((x.get('family'),x.get('tier'),x.get('runtime_revision'))==('sherpa-onnx','COMPACT',RUNTIME),'smoke identity drift'); req(x.get('runtime')=={'distribution':'sherpa-onnx','version':'1.13.7'},'smoke runtime drift'); req(x.get('primary_test_decoding_performed') is False and x.get('accuracy_scoring_performed') is False and x.get('comparative_ranking_present') is False and x.get('human_speech_used') is False and x.get('repository_context_used') is False,'smoke boundary drift'); req(x.get('artifacts')==ARTIFACTS,'smoke artifact drift')
def provenance()->None:
    req(P.stat().st_size==4944 and sha(P)==P_SHA,'provenance bytes drift'); p=load(P); u=dict(p); payload=u.pop('provenance_payload_sha256',None); req(payload==P_PAYLOAD and hashlib.sha256(canon(u)).hexdigest()==payload,'provenance payload drift'); req((p.get('schema_version'),p.get('task'),p.get('attempt_id'),p.get('candidate_id'))==('000b2-public-b2r09-provenance-v1','B2R09','000B2-PUBLIC-ATTEMPT-002','sherpa-onnx-compact'),'provenance identity drift')
    s=p['canonical_evidence_source']; req((s['workflow_id'],s['run_id'],s['job_id'],s['artifact_id'])==(WORKFLOW,SUCCESS_RUN,SUCCESS_JOB,ARTIFACT) and s['source_revision']==SUCCESS and s['artifact_zip_sha256']==ZIP_SHA and s['artifact_zip_size_bytes']==19519,'canonical source drift'); req(s['evidence_raw_file_sha256']==E_SHA and s['evidence_raw_file_size_bytes']==E_SIZE and s['evidence_payload_sha256']==PAYLOAD and s['selection_basis'].endswith('NOT_RESULT_DRIVEN'),'evidence provenance drift')
    f=p['failed_pre_primary_attempt']; req((f['workflow_id'],f['run_id'],f['job_id'],f['source_revision'])==(WORKFLOW,FAILED_RUN,FAILED_JOB,FAILED) and f['conclusion']=='failure' and f['pre_external_authority_passed'] is True and f['failure_stage']=='SETUP_PYTHON_CACHE_RESOLUTION','failed-run identity drift'); req(f['artifact_count']==0 and f['candidate_result_available'] is False and f['selection_effect']=='NONE','failed-run exposure drift');
    for k in ('runtime_install_started','preprocessing_container_pull_started','ffmpeg_fetch_started','preprocessing_execution_started','runtime_source_fetch_started','model_download_started','primary_decode_started','semantic_gate_started'): req(f[k] is False,f'failed run crossed {k}')
    r=p['forward_only_pre_primary_repair']; req((r['from_revision'],r['to_revision'])==(FAILED,SUCCESS) and r['changed_paths']==['.github/workflows/internal-b2r09-capture.yml'] and r['change']=='REMOVE_SETUP_PYTHON_CACHE_PIP_ONLY' and r['removed_yaml']=="cache: 'pip'",'repair record drift'); req(r['candidate_result_available_before_repair'] is False and r['candidate_result_inspection_before_repair'] is False and r['selection_effect']=='NONE','result-driven repair drift');
    for k in ('candidate_changed','model_changed','runtime_revision_changed','frozen_audio_membership_changed','frozen_audio_bytes_changed','c0_controls_changed','scorer_changed','normalization_changed'): req(r[k] is False,f'repair changed {k}')
    b=p['runtime_and_input_binding']; req(b['canonical_authority_base']==BASE and b['attempt_manifest_sha256']==ATTEMPT_SHA and b['attempt_freeze_digest_sha256']==FREEZE and b['preprocessing_capture_sha256']==PRE_SHA and b['b2r03_rebinding_sha256']==REBIND_SHA,'authority binding drift'); req(b['task_decoder_revision']==TASK_REV and b['task_decoder_blob_sha1']==DECODER_BLOB and b['sherpa_runtime_revision']==RUNTIME and b['sherpa_runtime_source_tree']==RUNTIME_TREE and b['onnx_model_revision']==ONNX and b['aux_model_revision']==AUX and b['operational_smoke_candidate_payload_sha256']==SMOKE_PAYLOAD,'runtime/model binding drift'); a=p['result_accounting']; req((a['input_count'],a['decoded_count'],a['failure_count'])==(240,240,0) and a['timing_semantics']=='DIAGNOSTIC_ONLY','provenance accounting drift');
    for k in ('reference_transcripts_loaded_by_decoder','accuracy_scoring_performed','comparative_ranking_present','performance_claim_present','result_driven_evidence_selection'): req(a[k] is False,f'provenance boundary drift {k}')
    req(p['claims']==CLAIMS,'provenance claims drift')
def evidence()->None:
    req(E.stat().st_size==E_SIZE and sha(E)==E_SHA,'evidence bytes drift'); e=load(E); u=dict(e); payload=u.pop('evidence_payload_sha256',None); req(payload==PAYLOAD and hashlib.sha256(canon(u)).hexdigest()==payload,'evidence payload drift'); req((e['schema_version'],e['task'],e['state'],e['attempt_id'])==('000b2-public-b2r09-decode-v1','B2R09','ATTEMPT_002_C0_PRIMARY_DECODE_CAPTURED','000B2-PUBLIC-ATTEMPT-002'),'evidence identity drift'); c=e['candidate']; req((c['cell_index'],c['candidate_id'],c['family'],c['tier'],c['model'])==(5,'sherpa-onnx-compact','sherpa-onnx','COMPACT','INT8 ONNX'),'candidate drift'); req(c['runtime_distribution']=='sherpa-onnx' and c['runtime_distribution_version']=='1.13.7' and c['runtime_revision']==RUNTIME and c['model_onnx_revision']==ONNX and c['model_aux_revision']==AUX and c['artifacts']==ARTIFACTS,'candidate/runtime/model drift')
    a=e['authority']; req(a['canonical_authority_base']==BASE and a['attempt_manifest_sha256']==ATTEMPT_SHA and a['attempt_freeze_digest_sha256']==FREEZE and a['preprocessing_capture_sha256']==PRE_SHA and a['b2r03_rebinding_sha256']==REBIND_SHA and a['operational_smoke_candidate_payload_sha256']==SMOKE_PAYLOAD,'evidence authority drift'); c0=e['c0_controls']; req(c0=={'candidate_specific_audio_transform_used':False,'decoding_method':'greedy_search','feature_dim':80,'feed_chunk_ms':500,'feed_chunk_samples':8000,'final_zero_chunk_samples':[8000,2560],'final_zero_pad_samples':10560,'hotwords':[],'identical_frozen_audio_required_across_candidates':True,'language':'en','language_model':None,'max_active_paths':4,'provider':'cpu','repository_context_used':False,'sample_rate_hz':16000,'test_specific_context_used':False,'threads':4},'C0 drift')
    run=e['run']; req(run['github_run_id']==SUCCESS_RUN and run['github_job']=='capture-b2r09' and run['repository_revision']==SUCCESS and run['github_ref']=='refs/heads/research/000b2-b2r09-execution' and run['python']=='3.11.16','run identity drift'); ri=run['runtime_identity']; req(ri['distribution']=='sherpa-onnx' and ri['version']=='1.13.7' and ri['source_revision']==RUNTIME and ri['source_tree']==RUNTIME_TREE and ri['module_file_sha256']=='9f1d820f337a09099a77e321d6ccddd0ea76b24ebaf815fb9a315cbb0a08b1f3','runtime identity drift'); req(run['timing_semantics']=='DIAGNOSTIC_ONLY' and run['comparative_performance_authorized'] is False,'timing claim drift')
    x=e['execution']; req((x['input_count'],x['decoded_count'],x['failure_count'])==(240,240,0) and x['all_frozen_input_hashes_reverified'] is True,'execution accounting drift');
    for k in ('reference_transcripts_loaded_by_decoder','accuracy_scoring_performed','comparative_ranking_present','performance_claim_present'): req(x[k] is False,f'evidence boundary drift {k}')
    rows=x['records']; req(isinstance(rows,list) and len(rows)==240,'record cardinality drift'); seen=set()
    for row in rows:
        uid=row.get('utterance_id'); req(isinstance(uid,str) and uid and uid not in seen,'utterance id drift'); seen.add(uid); d=row.get('canonical_preprocessed_file_sha256'); req(isinstance(d,str) and SHA64.fullmatch(d) is not None,f'preprocessed hash drift {uid}'); req(row.get('source_partition') in {'test-clean','test-other'} and row.get('status')=='DECODED' and row.get('failure') is None and isinstance(row.get('raw_transcript'),str) and isinstance(row.get('raw_stream_snapshots'),list),f'raw record drift {uid}'); t=row.get('feed_trace'); req(isinstance(t,dict) and t.get('sample_rate_hz')==16000 and t.get('zero_suffix_samples')==10560 and t.get('zero_suffix_chunk_samples')==[8000,2560] and t.get('input_finished') is True and isinstance(t.get('decode_steps'),int),f'feed trace drift {uid}'); req(isinstance(row.get('decode_wall_seconds'),(int,float)) and row['decode_wall_seconds']>=0,f'diagnostic timing drift {uid}')
    req(e['claim_guards']==CLAIMS,'evidence claims drift')
def main()->int:
    frontier(); static(); smoke(); provenance(); evidence(); print('B2R09_EVIDENCE=PASS'); return 0
if __name__=='__main__': raise SystemExit(main())
